@startuml Corrective RAG

'skinparam monochrome true
skinparam shadowing false
skinparam activity {
    StartColor limegreen
    EndColor darkblue
    BackgroundColor #d4de5e
    'BorderColor #5e94de
    'BackgroundColor #lightcyan
    BorderColor #lightblue
    ArrowColor black
}
skinparam activityDiamond {
    'BackgroundColor #5ede68
    'BorderColor #5e94de
    BackgroundColor #Pink
    BorderColor #Pink
    fontSize 12
}

start
-> start;

:retrieve;

:grade_document;

if (decide_to_generate) then (yes)    
else (no)
  :rewrite query;
  :web search;
endif

:generate;

-> end;
stop
@enduml