@startuml Corrective RAG
skinparam monochrome true

[*] -> retrieve : Start
retrieve -> grade_documents : Retrieve
grade_documents -> websearch
websearch -> generate
grade_documents -> generate
generate -> [*] : Stop 

'State1 : Description 1
'State2 : Description 2
'State3 : Description 3
@enduml